[package]
name = "actor-test"
version = "0.1.0"
authors = ["Ulf Lilleengen <ulf.lilleengen@gmail.com>"]
edition = "2018"

[dependencies]
heapless = "0.6"
generic-array = "0.14.4"
futures = { version = "0.3", features = ["executor"]}